# Generated by Django 3.2.6 on 2021-08-09 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportcardid',
            name='task_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
